### ISSUE TITLE
Install docs are all wrong

### ISSUE THREAD

**Issue by bbangert** [mozilla-services/autopush#179]
The Makefile doesn't work, the install docs say pypy is required (it isn't), etc. The docs should be updated to reflect a proper and working install method.

**Comment by ncalexan** [comment]
It appears that the suggested `moto_server` configuration does not work, either:
```
127.0.0.1 - - [05/Oct/2015 20:21:33] "POST http://dynamodb.us-east-1.amazonaws.com/ HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/Users/nalexander/Mozilla/autopush/pypy/lib/python2.7/site-packages/werkzeug/serving.py", line 180, in run_wsgi
    execute(self.server.app)
  File "/Users/nalexander/Mozilla/autopush/pypy/lib/python2.7/site-packages/werkzeug/serving.py", line 168, in execute
    application_iter = app(environ, start_response)
  File "/Users/nalexander/Mozilla/autopush/pypy/lib/python2.7/site-packages/moto/server.py", line 57, in __call__
    return backend_app(environ, start_response)
  File "/Users/nalexander/Mozilla/autopush/pypy/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/nalexander/Mozilla/autopush/pypy/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/nalexander/Mozilla/autopush/pypy/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nalexander/Mozilla/autopush/pypy/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nalexander/Mozilla/autopush/pypy/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nalexander/Mozilla/autopush/pypy/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nalexander/Mozilla/autopush/pypy/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nalexander/Mozilla/autopush/pypy/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nalexander/Mozilla/autopush/pypy/lib/python2.7/site-packages/moto/core/utils.py", line 77, in __call__
    result = self.callback(request, request.url, {})
  File "/Users/nalexander/Mozilla/autopush/pypy/lib/python2.7/site-packages/moto/core/responses.py", line 87, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/Users/nalexander/Mozilla/autopush/pypy/lib/python2.7/site-packages/moto/core/responses.py", line 128, in _dispatch
    return self.call_action()
  File "/Users/nalexander/Mozilla/autopush/pypy/lib/python2.7/site-packages/moto/dynamodb2/responses.py", line 62, in call_action
    response = getattr(self, endpoint)()
  File "/Users/nalexander/Mozilla/autopush/pypy/lib/python2.7/site-packages/moto/dynamodb2/responses.py", line 372, in update_item
    item = dynamodb_backend2.update_item(name, key, update_expression)
  File "/Users/nalexander/Mozilla/autopush/pypy/lib/python2.7/site-packages/moto/dynamodb2/models.py", line 416, in update_item
    item = table.get_item(hash_value)
  File "/Users/nalexander/Mozilla/autopush/pypy/lib/python2.7/site-packages/moto/dynamodb2/models.py", line 257, in get_item
    return self.items[hash_key]
  File "/Users/nalexander/Mozilla/autopush/pypy/lib/python2.7/site-packages/moto/dynamodb2/models.py", line 32, in __hash__
    return hash((self.type, self.value))
TypeError: unhashable type: 'dict'
```
(Although why this is trying to push to a live endpoint at all is beyond me.)

**Comment by jrconlin** [comment]
removed pypy dependencies, fixed install.rst file
https://github.com/mozilla-services/autopush/commit/ae5fd98a37f8adacba6f4a2ba2ec5ea0d3904ba8
