### ISSUE TITLE
Cannot run against local `moto_server` instance

### ISSUE THREAD

**Issue by ncalexan** [mozilla-services/autopush#263]
I start Moto with
```
nalexander@chocho ~/M/autopush> ./bin/moto_server dynamodb2 -p 5000
```
I start the endpoint server with
```
nalexander@chocho ~/M/autopush> ./bin/autoendpoint --gcm_enabled --senderid_list='{"1009375523940": {"auth": <ELIDED>}}' --s3_bucket=None --external_router
```
Moto complains:
```
127.0.0.1 - - [02/Dec/2015 13:26:22] "POST http://dynamodb.us-east-1.amazonaws.com/ HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/Users/nalexander/Mozilla/autopush/lib/python2.7/site-packages/werkzeug/serving.py", line 180, in run_wsgi
    execute(self.server.app)
  File "/Users/nalexander/Mozilla/autopush/lib/python2.7/site-packages/werkzeug/serving.py", line 168, in execute
    application_iter = app(environ, start_response)
  File "/Users/nalexander/Mozilla/autopush/src/moto/moto/server.py", line 53, in __call__
    return backend_app(environ, start_response)
  File "/Users/nalexander/Mozilla/autopush/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/nalexander/Mozilla/autopush/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/nalexander/Mozilla/autopush/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nalexander/Mozilla/autopush/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nalexander/Mozilla/autopush/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nalexander/Mozilla/autopush/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nalexander/Mozilla/autopush/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nalexander/Mozilla/autopush/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nalexander/Mozilla/autopush/src/moto/moto/core/utils.py", line 77, in __call__
    result = self.callback(request, request.url, {})
  File "/Users/nalexander/Mozilla/autopush/src/moto/moto/core/responses.py", line 87, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/Users/nalexander/Mozilla/autopush/src/moto/moto/core/responses.py", line 128, in _dispatch
    return self.call_action()
  File "/Users/nalexander/Mozilla/autopush/src/moto/moto/dynamodb2/responses.py", line 62, in call_action
    response = getattr(self, endpoint)()
  File "/Users/nalexander/Mozilla/autopush/src/moto/moto/dynamodb2/responses.py", line 337, in update_item
    item = dynamodb_backend2.update_item(name, key, update_expression, expression_attribute_values)
  File "/Users/nalexander/Mozilla/autopush/src/moto/moto/dynamodb2/models.py", line 441, in update_item
    hash_key, range_key = self.get_keys_value(table, key)
  File "/Users/nalexander/Mozilla/autopush/src/moto/moto/dynamodb2/models.py", line 400, in get_keys_value
    if table.hash_key_attr not in keys or (table.has_range_key and table.range_key_attr not in keys):
AttributeError: 'NoneType' object has no attribute 'hash_key_attr'
```

**Comment by bbangert** [comment]
moto_server can't be used, I've updated the docs to reflect that.
