### ISSUE TITLE
ssl test errors during initial test run

### ISSUE THREAD

**Issue by groovecoder** [mozilla-services/autopush#309]
I followed the instructions in the Installing and Testing docs.

I do not (think I) have a custom version of OpenSSL on Mac ...
```
(autopush)lcrouch:autopush lcrouch$ which openssl
/usr/bin/openssl
```
So, I did not set the `ARCHFLAGS`, `LDFLAGS`, nor `CFLAGS` environment variables.

When I ran `make test` I got these errors:
```
======================================================================
ERROR: test_ssl (autopush.tests.test_main.ConnectionMainTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/lcrouch/code/autopush/autopush/tests/test_main.py", line 113, in test_ssl
    ], False)
  File "/Users/lcrouch/code/autopush/autopush/main.py", line 412, in connection_main
    args.ssl_cert)
  File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/twisted/internet/ssl.py", line 104, in __init__
    self.cacheContext()
  File "/Users/lcrouch/code/autopush/autopush/ssl.py", line 50, in cacheContext
    ctx.set_options(SSL.OP_NO_COMPRESSION)
AttributeError: 'module' object has no attribute 'OP_NO_COMPRESSION'

...

======================================================================
ERROR: test_ssl (autopush.tests.test_main.EndpointMainTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/lcrouch/code/autopush/autopush/tests/test_main.py", line 190, in test_ssl
    "--s3_bucket=none",
  File "/Users/lcrouch/code/autopush/autopush/main.py", line 493, in endpoint_main
    args.ssl_cert)
  File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/twisted/internet/ssl.py", line 104, in __init__
    self.cacheContext()
  File "/Users/lcrouch/code/autopush/autopush/ssl.py", line 50, in cacheContext
    ctx.set_options(SSL.OP_NO_COMPRESSION)
AttributeError: 'module' object has no attribute 'OP_NO_COMPRESSION'
```

Can someone else try running the `make test` on a fresh clone & install of autopush? Or am I missing something obvious?

**Comment by jrconlin** [comment]
Hey Luke,

I just did a clone of automake into a new directory (I run Ubuntu 14.04)
and was able to do a "virtualenv .; make" successfully.

Ben might have more experience with the mac side, but the actual server
distribution is running on linux and I understand that there can be odd
issues with the way that macs are configured.

**Comment by kitcambridge** [comment]
Unfortunately, OS X ships with an older version of OpenSSL out of the box (on 10.9, `/usr/bin/openssl version` reports "OpenSSL 0.9.8zg"). I compiled 1.0.2e from source, but `brew install openssl` should work, too. I don't know if you need to recompile Python, too, but I don't think I had to do that.

Could you please try upgrading OpenSSL and see if that helps? We should probably note that in the docs, too. Sorry to make you jump through all these hoops.

**Comment by rpappalax** [comment]
if you've already brew installed the latest version of openssl, you'll still need to do a few extra steps:
see Note on OSX here:
http://autopush.readthedocs.org/en/latest/install.html
feel free to ping me if that doesn't work

**Comment by groovecoder** [comment]
`make` works fine either way.

I have OpenSSL 1.0.2d via `brew`:
```
lcrouch:code lcrouch$ /usr/local/opt/openssl/bin/openssl version
OpenSSL 1.0.2d 9 Jul 2015
```
`brew info openssl` gives me the proper environment variables to use:
```
    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include
```

But even with those environment variables set ...
```
lcrouch:autopush lcrouch$ echo $LDFLAGS
-L/usr/local/opt/openssl/lib
lcrouch:autopush lcrouch$ echo $CFLAGS
-I/usr/local/opt/openssl/include
lcrouch:autopush lcrouch$ echo $ARCHFLAGS
-arch x86_64
```
 I get 4 errors ...
```
======================================================================
ERROR: test_ssl (autopush.tests.test_main.ConnectionMainTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/lcrouch/code/autopush/autopush/tests/test_main.py", line 113, in test_ssl
    ], False)
  File "/Users/lcrouch/code/autopush/autopush/main.py", line 412, in connection_main
    args.ssl_cert)
  File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/twisted/internet/ssl.py", line 104, in __init__
    self.cacheContext()
  File "/Users/lcrouch/code/autopush/autopush/ssl.py", line 50, in cacheContext
    ctx.set_options(SSL.OP_NO_COMPRESSION)
AttributeError: 'module' object has no attribute 'OP_NO_COMPRESSION'
...
======================================================================
ERROR: test_ssl (autopush.tests.test_main.EndpointMainTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/lcrouch/code/autopush/autopush/tests/test_main.py", line 190, in test_ssl
    "--s3_bucket=none",
  File "/Users/lcrouch/code/autopush/autopush/main.py", line 493, in endpoint_main
    args.ssl_cert)
  File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/twisted/internet/ssl.py", line 104, in __init__
    self.cacheContext()
  File "/Users/lcrouch/code/autopush/autopush/ssl.py", line 50, in cacheContext
    ctx.set_options(SSL.OP_NO_COMPRESSION)
AttributeError: 'module' object has no attribute 'OP_NO_COMPRESSION'
...
======================================================================
ERROR: test_notification_results
----------------------------------------------------------------------
TimeoutError: <autopush.tests.test_websocket.WebsocketTestCase testMethod=test_notification_results> (test_notification_results) still running at 120.0 secs
...
======================================================================
ERROR: test_notification_results
----------------------------------------------------------------------
DirtyReactorAggregateError: Reactor was unclean.
DelayedCalls: (set twisted.internet.base.DelayedCall.debug = True to debug)
<DelayedCall 0x1202bb780 [0.026921749115s] called=0 cancelled=0 WebsocketTestCase._wait_for_message(<Deferred at 0x11af20040>)

traceback at creation:

  File ".tox/pypy/bin/nosetests", line 11, in <module>
    sys.exit(run_exit())
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
      File "/usr/local/Cellar/pypy/2.6.1/libexec/lib-python/2.7/unittest/main.py", line 95, in __init__
    self.runTests()
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/nose/core.py", line 62, in run
    test(result)
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/nose/suite.py", line 224, in run
    test(orig)
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/nose/suite.py", line 224, in run
    test(orig)
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/nose/suite.py", line 224, in run
    test(orig)
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/nose/suite.py", line 224, in run
    test(orig)
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/nose/suite.py", line 224, in run
    test(orig)
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/nose/case.py", line 45, in __call__
    return self.run(*arg, **kwarg)
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/nose/case.py", line 133, in run
    self.runTest(result)
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/nose/case.py", line 151, in runTest
    test(result)
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/twisted/trial/_asynctest.py", line 119, in __call__
    return self.run(*args, **kwargs)
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/twisted/trial/_synctest.py", line 1034, in run
    _collectWarnings(self._warnings.append, self._runFixturesAndTest, result)
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/twisted/trial/_synctest.py", line 183, in _collectWarnings
    result = f(*args, **kwargs)
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/twisted/trial/_asynctest.py", line 300, in _runFixturesAndTest
    self._wait(d)
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/twisted/trial/_asynctest.py", line 378, in _wait
    reactor.run()
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/twisted/internet/base.py", line 1201, in mainLoop
    self.runUntilCurrent()
      File "/Users/lcrouch/code/autopush/.tox/pypy/site-packages/twisted/internet/base.py", line 824, in runUntilCurrent
    call.func(*call.args, **call.kw)
      File "/Users/lcrouch/code/autopush/autopush/tests/test_websocket.py", line 82, in _wait_for_message
    reactor.callLater(0.1, self._wait_for_message, d)
```
I feel like I'm pretty much stuck. The only thing I can think is to re-compile python? Is that really the best option?

**Comment by rpappalax** [comment]
here's how i installed / ran tests on OSX:
https://gist.github.com/rpappalax/f53d22aabef9a8313c5e#file-autopush-install-osx-sh

**Comment by groovecoder** [comment]
It runs a lot faster that way, but I still get errors ...

https://gist.github.com/groovecoder/7aabbf1799edb8b5d84f

:cry: 

Something else to potentially note in the docs: make sure you're not running anything else on port 8000 when running tests or it will intercept everything trying to go to dynamodb.

**Comment by bbangert** [comment]
Closing in favor of #308 for doc clarification, as we can't attempt to work-around every OSX environment, but can do a better job of documenting the versions we test/run with.

**Comment by groovecoder** [comment]
Thanks, that makes sense to me.
