### ISSUE TITLE
throughput error on test_endpoint.py

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/autopush#318]
running Ubuntu 14.04.3 LTS
all tests pass, but test_endpoint throws exception.
Seeing same traceback in travis: https://travis-ci.org/mozilla-services/autopush/builds/105799157

----
pypy runtests: commands[0] | nosetests --with-object-tracker autopush
/home/rpapa/git/autopush/.tox/pypy/lib/python2.7/site-packages/cffi/model.py:526: UserWarning: 'point_conversion_form_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())
............................................Unhandled Error
Traceback (most recent call last):
  File "/home/rpapa/git/autopush/.tox/pypy/lib/python2.7/site-packages/twisted/internet/defer.py", line 578, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/rpapa/git/autopush/autopush/endpoint.py", line 411, in _route_notification
    d.callback(notification)
  File "/home/rpapa/git/autopush/.tox/pypy/lib/python2.7/site-packages/twisted/internet/defer.py", line 383, in callback
    self._startRunCallbacks(result)
  File "/home/rpapa/git/autopush/.tox/pypy/lib/python2.7/site-packages/twisted/internet/defer.py", line 491, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/rpapa/git/autopush/.tox/pypy/lib/python2.7/site-packages/twisted/internet/defer.py", line 578, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/rpapa/git/autopush/.tox/pypy/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/home/rpapa/git/autopush/.tox/pypy/lib/python2.7/site-packages/mock/mock.py", line 1128, in _mock_call
    ret_val = effect(*args, **kwargs)
  File "/home/rpapa/git/autopush/autopush/tests/test_endpoint.py", line 708, in raise_error
    errno=201
autopush.router.interface.RouterException: Provisioned throughput error

**Comment by bbangert** [comment]
Not reproducible.
