### ISSUE TITLE
intermittent test_no_delivery_to_unregistered failure under travis cpython 2.7.12

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/autopush#672]
We're geting a maybe harmless? intermittent WebSocketTimeoutException after upgrading to cpython 2.7.12 on travis:

I'm going to skip the test when it happens on there for now but it could use some further investigation. Might be handy to have timestamps in the tests' log messages.

```
======================================================================

ERROR: test_no_delivery_to_unregistered

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/mozilla-services/autopush/.tox/python/lib/python2.7/site-packages/twisted/internet/defer.py", line 1183, in _inlineCallbacks

    result = result.throwExceptionIntoGenerator(g)

  File "/home/travis/build/mozilla-services/autopush/.tox/python/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator

    return g.throw(self.type, self.value, self.tb)

  File "/home/travis/build/mozilla-services/autopush/autopush/tests/test_integration.py", line 861, in test_no_delivery_to_unregistered

    yield client.unregister(chan)

  File "/home/travis/build/mozilla-services/autopush/.tox/python/lib/python2.7/site-packages/twisted/python/threadpool.py", line 246, in inContext

    result = inContext.theWork()

  File "/home/travis/build/mozilla-services/autopush/.tox/python/lib/python2.7/site-packages/twisted/python/threadpool.py", line 262, in <lambda>

    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/home/travis/build/mozilla-services/autopush/.tox/python/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext

    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/home/travis/build/mozilla-services/autopush/.tox/python/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext

    return func(*args,**kw)

  File "/home/travis/build/mozilla-services/autopush/autopush/tests/test_integration.py", line 166, in unregister

    result = json.loads(self.ws.recv())

  File "/home/travis/build/mozilla-services/autopush/.tox/python/lib/python2.7/site-packages/websocket/_core.py", line 298, in recv

    opcode, data = self.recv_data()

  File "/home/travis/build/mozilla-services/autopush/.tox/python/lib/python2.7/site-packages/websocket/_core.py", line 315, in recv_data

    opcode, frame = self.recv_data_frame(control_frame)

  File "/home/travis/build/mozilla-services/autopush/.tox/python/lib/python2.7/site-packages/websocket/_core.py", line 328, in recv_data_frame

    frame = self.recv_frame()

  File "/home/travis/build/mozilla-services/autopush/.tox/python/lib/python2.7/site-packages/websocket/_core.py", line 360, in recv_frame

    return self.frame_buffer.recv_frame()

  File "/home/travis/build/mozilla-services/autopush/.tox/python/lib/python2.7/site-packages/websocket/_abnf.py", line 312, in recv_frame

    self.recv_header()

  File "/home/travis/build/mozilla-services/autopush/.tox/python/lib/python2.7/site-packages/websocket/_abnf.py", line 261, in recv_header

    header = self.recv_strict(2)

  File "/home/travis/build/mozilla-services/autopush/.tox/python/lib/python2.7/site-packages/websocket/_abnf.py", line 346, in recv_strict

    bytes = self.recv(min(16384, shortage))

  File "/home/travis/build/mozilla-services/autopush/.tox/python/lib/python2.7/site-packages/websocket/_core.py", line 429, in _recv

    return recv(self.sock, bufsize)

  File "/home/travis/build/mozilla-services/autopush/.tox/python/lib/python2.7/site-packages/websocket/_socket.py", line 80, in recv

    raise WebSocketTimeoutException(message)

WebSocketTimeoutException: timed out

-------------------- >> begin captured logging << --------------------

autopush.tests.test_integration: DEBUG: Send: {"use_webpush": true, "messageType": "hello", "uaid": "", "channelIDs": []}

autopush.tests.test_integration: DEBUG: Recv: {u'use_webpush': True, u'messageType': u'hello', u'uaid': u'fe4a5caa05054b0e94882f6de73f72a6', u'env': u'development', u'status': 200}

autopush.tests.test_integration: DEBUG: Send: {"key": null, "messageType": "register", "channelID": "b0379e4c-4c08-4f0d-bf42-481a4337a1f4"}

autopush.tests.test_integration: DEBUG: Recv: {u'messageType': u'register', u'pushEndpoint': u'http://localhost:9020/wpush/v1/gAAAAABX6V-WxzrDrt7phI2F_74EmupWTW9vPF5Hvz07MFqWUg90YIs5RTekHC0BZ-tW4_1B_9CVHpUnyzCL9WlQuo5RUKOpU7p7FUog2wdcfKWreJzj1v25PXfsJ_XAWoLNbstBrQq9', u'status': 200, u'channelID': u'b0379e4c-4c08-4f0d-bf42-481a4337a1f4'}

autopush.tests.test_integration: DEBUG: POST body: 2c40216f-a7ae-45f7-9f45-79d481448159

autopush.tests.test_integration: DEBUG: POST Response (201): 

autopush.tests.test_integration: DEBUG: Response Headers: [('content-type', 'text/html; charset=UTF-8'), ('date', 'Mon, 26 Sep 2016 17:49:10 GMT'), ('content-length', '0'), ('server', 'cyclone/1.1'), ('ttl', '200'), ('location', 'http://localhost:9020/m/gAAAAABX6V-WCqQVEKvqOA949wUHiRfQKtAxUWI_kigFhxA8ShbV5X9_E4r2X-gnzNXk9Orp6ty0sDZcqNLfqN2cJQ4Aho9_7rlHKUao04d15btGVKvVKW9aS5O8LlyNhGvmccM5H-z0X1lte1HzihhjyoO7RIUZP0vEkZ8GyGURew2BbJG7fWM=')]

autopush.tests.test_integration: DEBUG: Recv: {"headers": {"encryption": "keyid=\"http://example.org/bob/keys/123;salt=\"XZwpw6o37R-6qoZjw6KwAw\"", "crypto_key": "keyid=\"a1\"; dh=\"JcqK-OLkJZlJ3sJJWstJCA\"", "encoding": "aesgcm-128"}, "messageType": "notification", "version": "gAAAAABX6V-WCqQVEKvqOA949wUHiRfQKtAxUWI_kigFhxA8ShbV5X9_E4r2X-gnzNXk9Orp6ty0sDZcqNLfqN2cJQ4Aho9_7rlHKUao04d15btGVKvVKW9aS5O8LlyNhGvmccM5H-z0X1lte1HzihhjyoO7RIUZP0vEkZ8GyGURew2BbJG7fWM=:", "data": "MmM0MDIxNmYtYTdhZS00NWY3LTlmNDUtNzlkNDgxNDQ4MTU5", "channelID": "b0379e4c-4c08-4f0d-bf42-481a4337a1f4"}

autopush.tests.test_integration: DEBUG: Send: {"messageType": "ack", "updates": [{"version": "gAAAAABX6V-WCqQVEKvqOA949wUHiRfQKtAxUWI_kigFhxA8ShbV5X9_E4r2X-gnzNXk9Orp6ty0sDZcqNLfqN2cJQ4Aho9_7rlHKUao04d15btGVKvVKW9aS5O8LlyNhGvmccM5H-z0X1lte1HzihhjyoO7RIUZP0vEkZ8GyGURew2BbJG7fWM=:", "channelID": "b0379e4c-4c08-4f0d-bf42-481a4337a1f4"}]}

autopush.tests.test_integration: DEBUG: Send: {"messageType": "unregister", "channelID": "b0379e4c-4c08-4f0d-bf42-481a4337a1f4"}

--------------------- >> end captured logging << ---------------------
```

**Comment by pjenvey** [comment]
I'm going to assume 3ee93db solved this for now, if not we can reopen
