### ISSUE TITLE
test_main triggering NotImplementedError in calls to get_amid

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/autopush#935]
Running tests shows lots of calls to `get_amid()` happening when testing the endpoint, even if `no_aws` is set to `True`. 
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jrconlin/src/mozilla/push/autopush/lib/python2.7/site-packages/httpretty/core.py", line 637, in fill_filekind
    headers
  File "/home/jrconlin/src/mozilla/push/autopush/src/moto/moto/core/responses.py", line 285, in metadata_response
    raise NotImplementedError("The {0} metadata path has not been implemented".format(path))
NotImplementedError: The ami-id metadata path has not been implemented
```

**Comment by bbangert** [comment]
Closed by #987
